### ISSUE TITLE
Temperature compensation is not implemented

### ISSUE THREAD

**Issue by stanleyondrus** [DFRobot/DFRobot_PH#1]
The temperature compensation is not implemented.

**Comment by MkLHX** [comment]
Hi! Same finding today, but when i looked through the web about ph variation with temperature i can see the impact is really low on pH value.
[here](https://www.pasco.com/support/technical-support/technote/techIDlookup.cfm?TechNoteID=281) an example about pH variations.

**Comment by Arya11111** [comment]
#include "DFRobot_PH.h"
    #include <EEPROM.h>

    #define PH_PIN A1
    float voltage,phValue,temperature = 25;
    DFRobot_PH ph;

    void setup()
    {
        Serial.begin(115200);
        ph.begin();
    }

    void loop()
    {
        static unsigned long timepoint = millis();
        if(millis()-timepoint>1000U){                  //time interval: 1s
            timepoint = millis();
            //temperature = readTemperature();         // read your temperature sensor to execute temperature compensation
            voltage = analogRead(PH_PIN)/1024.0*5000;  // read the voltage
            phValue = ph.readPH(voltage,temperature);  // convert voltage to pH with temperature compensation
            Serial.print("temperature:");
            Serial.print(temperature,1);
            Serial.print("^C  pH:");
            Serial.println(phValue,2);
        }
        ph.calibration(voltage,temperature);           // calibration process by Serail CMD
    }

    float readTemperature()
    {
      //add your code here to get the temperature from your temperature sensor
    }
