### ISSUE TITLE
Rename example folder and add library.properties for Arduino Web IDE import

### ISSUE THREAD

**Issue by MiguelTolosa** [DFRobot/DFRobot_PH#4]
There are currently errors when trying to import the library into the Arduino create web IDE.

The first is the `example` folder should be renamed to `examples` in order to denote the zip as a library.
https://forum.arduino.cc/t/custom-library-no-such-file-or-directory/550399/7

The second is the repo needs a `library.properties` file for importing.
https://forum.arduino.cc/t/cant-upload-library-to-web-editor/589753

As described here
https://arduino.github.io/arduino-cli/0.19/library-specification/#libraryproperties-file-format

**Comment by mubarakabaz** [comment]
try using the library below, i use it safely. but it's just that i didn't find a bright spot of a way to set the appropriate value
[DFRobot_PH-master.zip](https://github.com/DFRobot/DFRobot_PH/files/8101173/DFRobot_PH-master.zip)

**Comment by MiguelTolosa** [comment]
I'm referring to the Arduino Web IDE, not the desktop IDE. The master zip for this repo does not work in the Web IDE.

**Comment by MiguelTolosa** [comment]
@z43740979 I created a PR for this fix.

https://github.com/DFRobot/DFRobot_PH/pull/5

**Comment by mubarakabaz** [comment]
or you could use the first version of the ph sensor code 
https://wiki.dfrobot.com/PH_meter_SKU__SEN0161_

**Comment by MiguelTolosa** [comment]
The library zip of my PR is working well, and the code you linked doesn't have calibration. 

I think programmatic calibration is necessary for the pH sensor to work as expected without requiring undue extra work from the user. If anyone wants to download a zip of my PR they are welcome to do so through the link I provided above.
