### ISSUE TITLE
Use of strupr

### ISSUE THREAD

**Issue by jacoboneill** [DFRobot/DFRobot_PH#6]
strupr is not supported on the DFRobot Firebeetle ESP8266 and isn't part of the ANSI Standard

**Comment by Arya11111** [comment]
Sorry， This library does not support esp8266  because its adc is not allowed. I have replaced the strupr function with the toUpperCase function, hope it helps.

**Comment by jacoboneill** [comment]
Hi @Arya11111
How come the adc doesn't allow it. Would like to know as I am going to go to another company as I can't get it to work.

Also, might be worth adding the ESP8266 to the unavailable in the README.md file

Thank you for the help anyway

**Comment by Arya11111** [comment]
Sorry, translation error. Actually, it's beacuse the measurement from esp8266 ADC is not accurate, so this library does not support it.

**Comment by Arya11111** [comment]
> Hi @Arya11111 How come the adc doesn't allow it. Would like to know as I am going to go to another company as I can't get it to work.
> 
> Also, might be worth adding the ESP8266 to the unavailable in the README.md file
> 
> Thank you for the help anyway

Sorry, translation error. Actually, it's beacuse the measurement from esp8266 ADC is not accurate, so this library does not support it.
